force-app/main/default/objects/CEMS_Internal_Scheduler__c/CEMS_Internal_Scheduler__c.object-meta.xml
<CustomObject>
    <label>Interview Scheduler</label>
    <nameField>
        <label>Interview Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interview Scheduler</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CEMS_Internal_Scheduler__c/fields/CEMS_Interview_End_Time__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Interview_End_Time__c</fullName>
    <label>Interview End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CEMS_Internal_Scheduler__c/fields/CEMS_Interview_Panel__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Interview_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Start typing the name or any relevant keyword of the panel member you want to include in the interview panel.</inlineHelpText>
    <label>Interview Panel</label>
    <referenceTo>CEMS_Interview_Panel__c</referenceTo>
    <relationshipLabel>Interview Scheduler</relationshipLabel>
    <relationshipName>Interview_Scheduler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEMS_Internal_Scheduler__c/fields/CEMS_Interview_Round__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Interview_Round__c</fullName>
    <label>Interview Round</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non Technical Round</fullName>
            </value>
            <value>
                <fullName>Technical Round</fullName>
            </value>
            <value>
                <fullName>HR Round</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEMS_Internal_Scheduler__c/fields/CEMS_Interview_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Interview_Start_Time__c</fullName>
    <label>Interview Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CEMS_Internal_Scheduler__c/fields/CEMS_Interview_Type__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Interview_Type__c</fullName>
    <label>Interview Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Person Interview</fullName>
            </value>
            <value>
                <fullName>Virtual Interview</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEMS_Interview_Panel__c/CEMS_Interview_Panel__c.object-meta.xml
<CustomObject>
    <label>Interview Panel</label>
    <nameField>
        <label>Interview Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interview Panel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CEMS_Interview_Panel__c/fields/CEMS_Interviewer_1__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Interviewer_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CEMS_Personnel__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CEMS_Personnel__c</referenceTo>
    <relationshipLabel>Interview Panel</relationshipLabel>
    <relationshipName>Interview_Panel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEMS_Interview_Panel__c/fields/CEMS_Personnel__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Personnel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personnel</label>
    <referenceTo>CEMS_Personnel__c</referenceTo>
    <relationshipLabel>Interview Panel (Personnel)</relationshipLabel>
    <relationshipName>Interview_Panel3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEMS_Interview_Panel__c/fields/CEMS_Position_Name__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Position_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position Name</label>
    <referenceTo>CEMS_Job_Opening__c</referenceTo>
    <relationshipLabel>Interview Panel</relationshipLabel>
    <relationshipName>Position_Name</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEMS_Job_Opening__c/CEMS_Job_Opening__c.object-meta.xml
<CustomObject>
    <label>Job Opening</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Openings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CEMS_Personnel__c/CEMS_Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnel</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CEMS_Personnel__c/fields/CEMS_Position__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>CEMS_Job_Opening__c</referenceTo>
    <relationshipLabel>Personnel</relationshipLabel>
    <relationshipName>Personnel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEMS_Personnel__c/fields/CEMS_Work_Email__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Work_Email__c</fullName>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/CEMSSchedulerControllerTest.cls
@isTest
public class CEMSSchedulerControllerTest {

     @isTest
    static void testGetInterviewData2() {
        CEMS_Job_Opening__c jobopening = new CEMS_Job_Opening__c();
        jobopening.Name = 'TestJobOpening';
        insert jobopening;
        CEMS_Personnel__c personnel = new CEMS_Personnel__c();
        personnel.Name = 'TestPersonnel';
        personnel.CEMS_Position__c = jobopening.Id;
        insert personnel;

        CEMS_Interview_Panel__c interviewPanel = new CEMS_Interview_Panel__c();
        interviewPanel.Name = 'TestPanel';
        interviewPanel.CEMS_Interviewer_1__c = personnel.Id;
        interviewPanel.CEMS_Position_Name__c = jobopening.Id;
        insert interviewPanel;
          
          
       

        CEMS_Internal_Scheduler__c interviewRecord = new CEMS_Internal_Scheduler__c();
        interviewRecord.Name = 'Interview Scheduler';
        interviewRecord.CEMS_Interview_Round__c = 'Technical Round';
        interviewRecord.CEMS_Interview_Type__c  = 'In Person Interview';
        interviewRecord.CEMS_Interview_Start_Time__c = Datetime.now();
        interviewRecord.CEMS_Interview_End_Time__c = interviewRecord.CEMS_Interview_Start_Time__c.addMinutes(30);
        interviewRecord.CEMS_Interview_Panel__c = interviewPanel.Id;
        insert interviewRecord;                                                                                    

        // Call the method to be tested
        Test.startTest();
        List<CEMS_Internal_Scheduler__c> result = CEMSSchedulerController.getInterviewData2(personnel.CEMS_Work_Email__c);
        Test.stopTest();

        // Verify the result
        System.assertEquals(1, result.size(), 'Number of interview records should be 1');
        

    }
    
    @isTest
    static void testGetInterviewData() {
        CEMS_Job_Opening__c jobopening = new CEMS_Job_Opening__c();
        jobopening.Name = 'TestJobOpening';
        insert jobopening;
        CEMS_Personnel__c personnel = new CEMS_Personnel__c();
        personnel.Name = 'TestPersonnel';
        personnel.CEMS_Position__c = jobopening.Id;
        insert personnel;

        CEMS_Interview_Panel__c interviewPanel = new CEMS_Interview_Panel__c();
        interviewPanel.Name = 'TestPanel';
        interviewPanel.CEMS_Interviewer_1__c = personnel.Id;
        interviewPanel.CEMS_Position_Name__c = jobopening.Id;
        insert interviewPanel;
          
          
       

        CEMS_Internal_Scheduler__c interviewRecord = new CEMS_Internal_Scheduler__c();
        interviewRecord.Name = 'Interview Scheduler';
        interviewRecord.CEMS_Interview_Round__c = 'Technical Round';
        interviewRecord.CEMS_Interview_Type__c  = 'In Person Interview';
        interviewRecord.CEMS_Interview_Start_Time__c = Datetime.now();
        interviewRecord.CEMS_Interview_End_Time__c = interviewRecord.CEMS_Interview_Start_Time__c.addMinutes(30);
        interviewRecord.CEMS_Interview_Panel__c = interviewPanel.Id;
        insert interviewRecord;                                                                                    

        // Call the method to be tested
        Test.startTest();
        List<CEMS_Internal_Scheduler__c> result = CEMSSchedulerController.getInterviewData2(personnel.CEMS_Work_Email__c);
        Test.stopTest();

        // Verify the result
        System.assertEquals(1, result.size(), 'Number of interview records should be 1');
    }
    
    
}