force-app/main/default/objects/CEMS_Job_Application__c/CEMS_Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{000}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CEMS_Job_Application__c/fields/CEMS_Job_Opening__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Job_Opening__c</fullName>
    <label>Job Opening</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>External Job Application</value>
        </filterItems>
        <filterItems>
            <field>CEMS_Job_Opening__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>External Job Opening</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Job Application</value>
        </filterItems>
        <filterItems>
            <field>CEMS_Job_Opening__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Job Opening</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CEMS_Job_Opening__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CEMS_Job_Application__c/fields/CEMS_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEMS_Job_Application__c/fields/CEMS_Personnel__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Personnel__c</fullName>
    <label>Personnel</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>External Job Application</value>
        </filterItems>
        <filterItems>
            <field>CEMS_Personnel__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Applicant</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Job Application</value>
        </filterItems>
        <filterItems>
            <field>CEMS_Personnel__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CEMS_Personnel__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CEMS_Job_Application__c/fields/Offered_Position__c.field-meta.xml
<CustomField>
    <fullName>Offered_Position__c</fullName>
    <label>Offered Position</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEMS_Job_Application__c/fields/Offered_salary__c.field-meta.xml
<CustomField>
    <fullName>Offered_salary__c</fullName>
    <label>Offered salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CEMS_Job_Opening__c/CEMS_Job_Opening__c.object-meta.xml
<CustomObject>
    <label>Job Opening</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Openings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CEMS_Job_Opening__c/fields/CEMS_Job_Location__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Job_Location__c</fullName>
    <label>Job Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEMS_Personnel__c/CEMS_Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnel</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CEMS_Personnel__c/fields/CEMS_Email__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/EmailSenderTest.cls
@isTest
private class EmailSenderTest {
 @isTest
    static void testSendOfferLetterEmail() {
        // Create test data
        CEMS_Personnel__c personnelRecord = new CEMS_Personnel__c(
            // Provide required field values
            // ...
        );
        insert personnelRecord;
        CEMS_Job_Opening__c jobOpening = new CEMS_Job_Opening__c(
            CEMS_Job_Location__c = 'Mumbai'
            // Add other required fields...
        );
        insert jobOpening;

        CEMS_Job_Application__c jobApplication = new CEMS_Job_Application__c(
            CEMS_Email__c = 'test@example.com',
            Offered_Position__c = 'Sales Cloud Consultant',
            CEMS_Last_Name__c = 'Doe',
            Date_of_Joining__c = Date.today(),
            Offered_salary__c = 80000.00,
            CEMS_Personnel__c = personnelRecord.Id,
            CEMS_Job_Opening__c = jobOpening.Id // Assign the Id of a CEMS_Job_Opening__c record
        );
        insert jobApplication;

         // Call the method within System.runAs to isolate the test execution
        Test.startTest();
        System.runAs(new User(Id = UserInfo.getUserId())) {
            EmailSender.sendOfferLetterEmail([SELECT Id FROM CEMS_Job_Application__c LIMIT 1].Id);
        }
        Test.stopTest();

        // Query sent emails using @seeAllData
        List<EmailMessage> sentEmails = [SELECT Subject FROM EmailMessage];
        
        // Check if any emails were sent
        System.assertEquals(1, sentEmails.size(), 'Expected one email to be sent');

        // Check the subject of the sent email
        System.assertEquals('Offer Letter for Software Engineer role at CittaCore Technologies','Offer Letter for Software Engineer role at CittaCore Technologies', sentEmails[0].Subject);
    
    }

    @isTest
    static void testGenerateOfferLetter() {
        // Call the generateOfferLetter method and check its output
        String offerLetter = EmailSender.generateOfferLetter('Software Engineer', 'Doe', Date.today(), 80000.00);

        // Add your assertions here based on the expected content of the generated offer letter
        // For example, you can check if certain phrases or values are present in the offer letter

        // Example assertion for checking if the offer letter contains the position name
        System.assert(offerLetter.contains('Congratulations! You have been selected for the Software Engineer position at CittaCore Technologies'));
    }
}