force-app/main/default/objects/CEMS_Award__c/CEMS_Award__c.object-meta.xml
<CustomObject>
    <label>Award</label>
    <nameField>
        <label>Award Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CEMS_Employee_Award__c/CEMS_Employee_Award__c.object-meta.xml
<CustomObject>
    <label>Employee Award</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Employee Award ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CEMS_Employee_Award__c/fields/CEMS_Award__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Award__c</fullName>
    <label>Award</label>
    <referenceTo>CEMS_Award__c</referenceTo>
    <relationshipLabel>Employee Awards</relationshipLabel>
    <relationshipName>Employee_Awards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CEMS_Employee_Award__c/fields/CEMS_Award_Date__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Award_Date__c</fullName>
    <label>Award Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CEMS_Employee_Award__c/fields/CEMS_Award_URL__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Award_URL__c</fullName>
    <label>Award URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CEMS_Employee_Award__c/fields/CEMS_Employee__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Employee__c</fullName>
    <label>Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CEMS_Personnel__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CEMS_Personnel__c</referenceTo>
    <relationshipLabel>Employee Awards</relationshipLabel>
    <relationshipName>Employee_Awards</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CEMS_Employee_Project__c/CEMS_Employee_Project__c.object-meta.xml
<CustomObject>
    <label>Employee Projects</label>
    <nameField>
        <displayFormat>EP-{0000}</displayFormat>
        <label>Employee Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CEMS_Employee_Project__c/fields/CEMS_Employee__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Employee__c</fullName>
    <label>Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CEMS_Personnel__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CEMS_Personnel__c</referenceTo>
    <relationshipLabel>Employee Projects</relationshipLabel>
    <relationshipName>Employee_Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CEMS_Employee_Project__c/fields/CEMS_Employee_s_Project_End_Date__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Employee_s_Project_End_Date__c</fullName>
    <label>Employee&apos;s Project End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CEMS_Employee_Project__c/fields/CEMS_Employee_s_Project_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Employee_s_Project_Start_Date__c</fullName>
    <label>Employee&apos;s Project Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CEMS_Employee_Project__c/fields/CEMS_Project_Role__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Project_Role__c</fullName>
    <label>Project Role</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CEMS_Employee_Project__c/fields/CEMS_Projects__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Projects__c</fullName>
    <label>Projects</label>
    <referenceTo>CEMS_Projects__c</referenceTo>
    <relationshipName>Employee_Projects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CEMS_Job_Opening__c/CEMS_Job_Opening__c.object-meta.xml
<CustomObject>
    <label>Job Opening</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Openings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CEMS_Job_Opening__c/fields/CEMS_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEMS_Job_Opening__c/fields/CEMS_Available_Vacancies__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Available_Vacancies__c</fullName>
    <label>Available Vacancies</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CEMS_Job_Opening__c/fields/CEMS_Experience__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Experience__c</fullName>
    <label>Experience</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0-1 Yr</fullName>
            </value>
            <value>
                <fullName>1-3 Yrs</fullName>
            </value>
            <value>
                <fullName>4-7 Yrs</fullName>
            </value>
            <value>
                <fullName>7-10 Yrs</fullName>
            </value>
            <value>
                <fullName>10+ Yrs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEMS_Job_Opening__c/fields/CEMS_Job_Location__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Job_Location__c</fullName>
    <label>Job Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEMS_Job_Opening__c/fields/CEMS_Roles_and_Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Roles_and_Responsibilities__c</fullName>
    <label>Roles and Responsibilities</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CEMS_Job_Opening__c/fields/CEMS_Skills__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Skills__c</fullName>
    <label>Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CEMS_Skills</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEMS_Job_Opening__c/fields/CEMS_Status__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Filled/Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEMS_Job_Opening__c/fields/CEMS_Technology__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Technology__c</fullName>
    <label>Technology</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Amazon Web Services</fullName>
            </value>
            <value>
                <fullName>Azure</fullName>
            </value>
            <value>
                <fullName>Oracle Cloud</fullName>
            </value>
            <value>
                <fullName>Google Cloud</fullName>
            </value>
            <value>
                <fullName>IBM Cloud</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEMS_Performance__c/CEMS_Performance__c.object-meta.xml
<CustomObject>
    <label>Performance</label>
    <nameField>
        <label>Performance Review Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CEMS_Performance__c/fields/CEMS_Employee__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Employee__c</fullName>
    <label>Personnel</label>
    <referenceTo>CEMS_Personnel__c</referenceTo>
    <relationshipLabel>Performance</relationshipLabel>
    <relationshipName>Performance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CEMS_Personnel__c/CEMS_Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnel</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CEMS_Personnel__c/fields/CEMS_Experience__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Experience__c</fullName>
    <label>Work Experience</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEMS_Personnel__c/fields/CEMS_Status__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Joined</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEMS_Personnel__c/fields/CEMS_Work_Email__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Work_Email__c</fullName>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CEMS_Personnel__c/recordTypes/Employee.recordType-meta.xml
<RecordType>
    <fullName>Employee</fullName>
    <active>true</active>
    <label>Employee</label>
</RecordType>

force-app/main/default/objects/CEMS_Projects__c/CEMS_Projects__c.object-meta.xml
<CustomObject>
    <label>Projects</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Training__c/Employee_Training__c.object-meta.xml
<CustomObject>
    <label>Employee Training</label>
    <nameField>
        <displayFormat>ET-{0000}</displayFormat>
        <label>Employee Training ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Training__c/fields/CEMS_Certification_Name__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Certification_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Certification Name</label>
    <referenceTo>CEMS_Training__c</referenceTo>
    <relationshipLabel>Employee Trainings</relationshipLabel>
    <relationshipName>Employee_Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/fields/CEMS_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Due_Date__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/fields/CEMS_Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Employee_Name__c</fullName>
    <label>Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CEMS_Personnel__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CEMS_Personnel__c</referenceTo>
    <relationshipLabel>Employee Trainings</relationshipLabel>
    <relationshipName>Employee_Trainings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/fields/CEMS_Learning_Name__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Learning_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Learning Name</label>
    <referenceTo>CEMS_Training__c</referenceTo>
    <relationshipLabel>Employee Trainings (Learning Name)</relationshipLabel>
    <relationshipName>Employee_Trainings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/fields/CEMS_Status__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Yet Started</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CEMS_Skills.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apex Development</fullName>
    </customValue>
    <customValue>
        <fullName>Configuration</fullName>
    </customValue>
    <customValue>
        <fullName>Debugging and Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Security and Access</fullName>
    </customValue>
    <customValue>
        <fullName>Visualforce Pages</fullName>
    </customValue>
    <customValue>
        <fullName>Process Automation</fullName>
    </customValue>
    <customValue>
        <fullName>Data Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Management</fullName>
    </customValue>
    <customValue>
        <fullName>Care Plan Management</fullName>
    </customValue>
    <customValue>
        <fullName>Case Management</fullName>
    </customValue>
    <customValue>
        <fullName>Knowledge Management</fullName>
    </customValue>
    <customValue>
        <fullName>Opportunity Management</fullName>
    </customValue>
    <customValue>
        <fullName>Account Management</fullName>
    </customValue>
    <customValue>
        <fullName>Lightning Components</fullName>
    </customValue>
    <customValue>
        <fullName>Product Configuration</fullName>
    </customValue>
    <customValue>
        <fullName>Pricing Rules</fullName>
    </customValue>
    <masterLabel>Skills</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
public class TestDataFactory {

    // Method to set up a REST request with the given request URI and parameters
    @TestVisible
    public static RestRequest setupRestRequest(String requestURI, Map<String, String> params) {
        RestRequest req = new RestRequest();
        req.requestURI = requestURI;
        req.params.putAll(params);
        RestContext.request = req;
        return req;
    }

    // Method to set up a REST response
    @TestVisible
    public static RestResponse setupRestResponse() {
        RestResponse res = new RestResponse();
        RestContext.response = res;
        return res;
    }

    // Method to create test data for job openings
    @TestVisible
    public static void createTestData() {
        List<CEMS_job_opening__c> jobOpeningsData = new List<CEMS_job_opening__c>();
        for (Integer i = 0; i < 15; i++) {
            CEMS_job_opening__c jobOpening = new CEMS_job_opening__c(
                Name = 'Job Opening ' + i,
                CEMS_Roles_and_Responsibilities__c = 'Responsibilities for Job ' + i,
                CEMS_Skills__c = 'Configuration ',
                CEMS_Status__c = 'Open',
                CEMS_Technology__c = 'Azure',
                CEMS_Job_Location__c = 'Pune',
                CEMS_Available_Vacancies__c = 3,
                CEMS_Experience__c = '0-2 years'
            );
            jobOpeningsData.add(jobOpening);
        }
        insert jobOpeningsData;
    }

    // Method to create bulk test data for job openings
    @TestVisible
    public static void createBulkData() {
        List<CEMS_job_opening__c> jobOpenings = new List<CEMS_job_opening__c>();
        jobOpenings.add(new CEMS_job_opening__c(
            Name = 'Test Job 1',
            CEMS_Roles_and_Responsibilities__c = 'Test Roles and Responsibilities 1',
            CEMS_Technology__c = 'Azure',
            CEMS_Status__c = 'Open',
            CEMS_Job_Location__c = 'Pune',
            CEMS_Available_Vacancies__c = 5,
            CEMS_Experience__c = '1-2 years'
        ));
        jobOpenings.add(new CEMS_job_opening__c(
            Name = 'Test Job 2',
            CEMS_Roles_and_Responsibilities__c = 'Test Roles and Responsibilities 2',
            CEMS_Technology__c = 'Azure',
            CEMS_Status__c = 'Open',
            CEMS_Job_Location__c = 'Pune',
            CEMS_Available_Vacancies__c = 0,
            CEMS_Experience__c = '1-3 years'
        ));
        insert jobOpenings;
    }
    @TestVisible
     public static List<CEMS_Job_Opening__c> createApprovedJobOpenings(Integer numberOfRecords) {
        List<CEMS_Job_Opening__c> jobList = new List<CEMS_Job_Opening__c>();

        for (Integer i = 0; i < numberOfRecords; i++) {
            CEMS_Job_Opening__c job = new CEMS_Job_Opening__c(
                Name = 'Slesforce Developers ' + i,
                CEMS_Technology__c = 'Salesforce'
                //CEMS_Approval_Status__c = 'Approved'
                // Add other required fields as needed
            );
            jobList.add(job);
        }

        insert jobList;
        return jobList;
}
    // Create a test user
    @TestVisible
    public static User createTestUser(String email, String profileName) {
        Profile testProfile = [SELECT Id FROM Profile WHERE Name = :profileName LIMIT 1];

        // Append a timestamp to ensure a unique username
        String uniqueUsername = email + System.now().millisecond();

        User testUser = new User(
            FirstName = 'Test',
            LastName = 'User',
            Email = email,
            Username = uniqueUsername,
            Alias = 'TUser',
            ProfileId = testProfile.Id,
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'America/Los_Angeles'
        );

        insert testUser;

        return testUser;
    }

    // Create a test CEMS_Employee__c record
    public static CEMS_Personnel__c createTestEmployee(Id userId) {
        CEMS_Personnel__c testEmployee = new CEMS_Personnel__c(
            Name = 'Test Employee',
            cems_work_email__c = 'testuser@example.com'
            // Add other required fields
        );

        insert testEmployee;

        return testEmployee;
    }

    // Create a test CEMS_Performance__c record
        @TestVisible

    public static CEMS_Performance__c createTestPerformance(Id employeeId) {
        CEMS_Performance__c testPerformance = new CEMS_Performance__c(
            // Populate fields as needed
            CEMS_Employee__c = employeeId
        );

        insert testPerformance;

        return testPerformance;
    }
    @TestVisible
 public static List<Employee_Training__c> createTestTrainings(Id employeeId) {
    List<Employee_Training__c> trainings = new List<Employee_Training__c>();

    // Create one or more Employee_Training__c records related to the employee
    for (Integer i = 0; i < 5; i++) {
                    System.debug('employeeId::::'+employeeId);

        trainings.add(new Employee_Training__c(
            CEMS_Employee_Name__c = employeeId,
           // CEMS_Learning_Name__c = 'Learning ' + i,
           // CEMS_Certification_Name__c = 'Certification ' + i,
            CEMS_Status__c = 'Completed',
            CEMS_Due_Date__c = Date.today().addDays(30)
        ));
    }

    insert trainings;
    return trainings;
}
    @TestVisible
 public static CEMS_Job_Opening__c createJobOpening(String jobName, String approvalStatus) {
        CEMS_Job_Opening__c jobOpening = new CEMS_Job_Opening__c(
            Name = jobName,
            CEMS_Approval_Status__c = approvalStatus
        );
        insert jobOpening;
        return jobOpening;
    }
    
     public static CEMS_Personnel__c createEmployee(String email) {
        CEMS_Personnel__c employee = new CEMS_Personnel__c(
            Name = 'Test Employee',
            cems_work_email__c = email
        );
        insert employee;
        return employee;
    }

    public static CEMS_Award__c createAward() {
        CEMS_Award__c award = new CEMS_Award__c(
            Name = 'Test Award'
            // Add other required fields
        );
        insert award;
        return award;
    }

    public static CEMS_Employee_Award__c createEmployeeAward(String employeeId, String awardId) {
        CEMS_Employee_Award__c employeeAward = new CEMS_Employee_Award__c(
            CEMS_Award__c = awardId,
            CEMS_Employee__c = employeeId,
            CEMS_Award_Date__c = Date.today(),
            CEMS_Award_URL__c = 'https://example.com'
            // Add other required fields
        );
        insert employeeAward;
        return employeeAward;
    }
    
   /* public static CEMS_Personnel__c createTestEmployee(Id userId) {
        CEMS_Personnel__c testEmployee = new CEMS_Personnel__c(
            Name = 'Test Employee',
            cems_work_email__c = 'testemployee@example.com'
            // Add other required fields
        );

        insert testEmployee;
        return testEmployee;
    }*/


   
public static CEMS_Employee_Project__c createEmployeeProject(CEMS_personnel__c employee, CEMS_Projects__c project) {
    CEMS_Employee_Project__c employeeProject = new CEMS_Employee_Project__c();
    employeeProject.CEMS_Employee__c = employee.Id;
    employeeProject.CEMS_Projects__c = project.Id;
    employeeProject.CEMS_Employee_s_Project_Start_Date__c = Date.today();  // Replace with the actual start date
    employeeProject.CEMS_Employee_s_Project_End_Date__c = Date.today().addDays(10);  // Replace with the actual end date
    employeeProject.CEMS_Project_Role__c = 'Project Role';  // Replace with the actual role
    // Add any other required fields for CEMS_Employee_Project__c
    insert employeeProject;
    return employeeProject;
}
public static CEMS_Projects__c createTestProject() {
        CEMS_Projects__c project = new CEMS_Projects__c(
            // Set any required fields for CEMS_Projects__c
            Name = 'Test Project'
        );
        insert project;
        return project;
    }
}