force-app/main/default/objects/CEMS_Interview_Panel__c/CEMS_Interview_Panel__c.object-meta.xml
<CustomObject>
    <label>Interview Panel</label>
    <nameField>
        <label>Interview Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interview Panel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CEMS_Interview_Panel__c/fields/CEMS_Interviewer_1__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Interviewer_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CEMS_Personnel__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CEMS_Personnel__c</referenceTo>
    <relationshipLabel>Interview Panel</relationshipLabel>
    <relationshipName>Interview_Panel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEMS_Interview_Panel__c/fields/CEMS_Interviewer_2__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Interviewer_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CEMS_Personnel__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CEMS_Personnel__c</referenceTo>
    <relationshipLabel>Interview Panel (Interviewer 2)</relationshipLabel>
    <relationshipName>Interview_Panel1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEMS_Interview_Panel__c/fields/CEMS_Interviewer_3__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Interviewer_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CEMS_Personnel__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CEMS_Personnel__c</referenceTo>
    <relationshipLabel>Interview Panel (Interviewer 3)</relationshipLabel>
    <relationshipName>Interview_Panel2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEMS_Interview_Panel__c/fields/CEMS_Personnel__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Personnel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personnel</label>
    <referenceTo>CEMS_Personnel__c</referenceTo>
    <relationshipLabel>Interview Panel (Personnel)</relationshipLabel>
    <relationshipName>Interview_Panel3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEMS_Interview_Panel__c/fields/CEMS_Position_Name__c.field-meta.xml
<CustomField>
    <fullName>CEMS_Position_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position Name</label>
    <referenceTo>CEMS_Job_Opening__c</referenceTo>
    <relationshipLabel>Interview Panel</relationshipLabel>
    <relationshipName>Position_Name</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEMS_Job_Opening__c/CEMS_Job_Opening__c.object-meta.xml
<CustomObject>
    <label>Job Opening</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Openings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CEMS_Personnel__c/CEMS_Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnel</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/InterviewPanelControllerTest.cls
@isTest
public class InterviewPanelControllerTest {

    @isTest
    static void testGetInterviewPanels() {
        // Test data setup
        CEMS_Job_Opening__c jobOpening = new CEMS_Job_Opening__c(Name = 'TestJobOpening');
        insert jobOpening;

        CEMS_Personnel__c interviewer1 = new CEMS_Personnel__c(Name = 'Interviewer1');
        insert interviewer1;

        CEMS_Personnel__c interviewer2 = new CEMS_Personnel__c(Name = 'Interviewer2');
        insert interviewer2;

        CEMS_Personnel__c interviewer3 = new CEMS_Personnel__c(Name = 'Interviewer3');
        insert interviewer3;

        CEMS_Interview_Panel__c interviewPanel = new CEMS_Interview_Panel__c(
            Name = 'TestPanel',
            CEMS_Interviewer_1__c = interviewer1.Id,
            CEMS_Interviewer_2__c = interviewer2.Id,
            CEMS_Interviewer_3__c = interviewer3.Id,
            CEMS_Position_Name__c = jobOpening.Id
        );
        insert interviewPanel;

        // Call the method to be tested
        Test.startTest();
        List<CEMS_Interview_Panel__c> result = InterviewPanelController.getInterviewPanels();
        Test.stopTest();

        // Verify the result
        System.assertEquals(1, result.size(), 'Number of interview panels should be 1');

        // Additional assertions based on your specific requirements
        // ...

        // Ensure the debug statements are covered
        // (optional, remove in production code)
        for (CEMS_Interview_Panel__c panel : result) {
            System.assertNotEquals(null, panel.Id);
            System.assertNotEquals(null, panel.Name);
            System.assertNotEquals(null, panel.CEMS_Interviewer_1__r.Name);
            System.assertNotEquals(null, panel.CEMS_Interviewer_2__r.Name);
            System.assertNotEquals(null, panel.CEMS_Interviewer_3__r.Name);
            System.assertNotEquals(null, panel.CEMS_Position_Name__r.Name);
        }
    }
}